name: big-trees

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - cmocean
  - descartes
  - gcsfs
  - gdal
  - geopandas
  - ipython
  - jupyter
  - matplotlib
  - pandas
  - r-base
  - r-essentials
  - r-irkernel
  - rasterio
  - rtree
  - scikit-learn
  - scipy
  - shapely
  - tqdm
  - pip
  - pip:
    - cfo
    - elapid
    - giants
    - git+https://github.com/digital-idiot/RotationForest.git
